import React from 'react';
import counterpart from 'counterpart';
import { Markdown } from 'markdownz';

const HowToBuildProject = () =>
  (<div className="on-secondary-page">
    <Markdown>{counterpart('lab.help.howToBuildProject.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.quickGuide')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.navigating')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.projectDetails')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.about')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.collaborators')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.tutorial')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.media')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.visibility')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.workflows')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.orientation')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.createTasks')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.taskContent')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.questions')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.drawing')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.transcription')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.linking')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.subjectSets')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.overview.inDetail.furtherHelp')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.sectionOverview.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.sectionOverview.quickGuide')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.sectionOverview.navigating')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.sectionOverview.inDetail')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step1')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step2')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step3')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step4')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step5')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step6')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step7')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step8')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step9')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step10')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.quickGuide.step11')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.navigatingTheProjectBuilder.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.navigatingTheProjectBuilder.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.navigatingTheProjectBuilder.project')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.navigatingTheProjectBuilder.workflows')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.navigatingTheProjectBuilder.subjectSets')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.navigatingTheProjectBuilder.glossaryPage')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.details')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.about')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.collaborators')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.fieldGuide')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.tutorial')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.media')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.visibility')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.talk')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.project.dataExports')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.workflows.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.workflows.body')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.subjects.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.subjects.body')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectBuildingInDetail')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.name')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.avatar')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.background')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.description')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.introduction')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.workflowDescription')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.checkboxVolunteers')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.researcherQuote')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.announcementBanner')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.disciplineTag')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.otherTags')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.externalLinks')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.socialLinks')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.projectDetails.checkboxPrivate')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.about.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.about.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.about.research')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.about.team')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.about.results')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.about.education')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.about.faq')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.collaborators.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.collaborators.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.collaborators.owner')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.collaborators.collaborator')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.collaborators.expert')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.collaborators.researcher')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.collaborators.moderator')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.collaborators.tester')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.collaborators.translator')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.fieldGuide.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.fieldGuide.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.fieldGuide.details')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.tutorial.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.tutorial.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.tutorial.details')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.media.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.media.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.visibility.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.visibility.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.visibility.projectState')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.visibility.betaStatus')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.visibility.workflowSettings')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.talk.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.talk.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.talk.details')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.dataExports.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.dataExports.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.workflow.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.workflow.introduction')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.workflow.workflowTitle')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.workflow.version')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.workflow.tasks')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.workflow.mainText')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.workflow.helpText')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.createTasks.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.createTasks.body')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.taskContent.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.taskContent.body')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.questions.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.questions.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.questions.required')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.questions.multiple')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.questions.nextTask')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.bezier')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.circle')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.column')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.ellipse')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.line')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.point')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.polygon')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.rectangle')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.triangle')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.drawing.gridTable')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.transcription.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.transcription.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.transcription.keywordTagging')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.transcription.fullTextTranscription')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.transcription.aggregatedClassifications')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.linking.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.linking.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.linking.multiImageOptions')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.linking.subjectRetirement')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.subjectSets.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.subjectSets.intro')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.subjectSets.details')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.furtherHelp.title')}</Markdown>
    <Markdown>{counterpart('lab.help.howToBuildProject.furtherHelp.body')}</Markdown>
  </div>);

export default HowToBuildProject;
