/*
  The majority of project slugs are in this list because they are private projects
  who want to use the private project feature available only in PFE, not FEM. The rest
  are "held back" on PFE due to an unsupported classifier feature or subject type.

  See also https://github.com/zooniverse/static/blob/master/nginx-private-project-redirects.conf
  and https://github.com/zooniverse/static/blob/master/nginx-special-redirects.conf
*/

const PFE_SLUGS = [
  // Projects with a project.redirect property
  'zooniverse/moon-zoo',
  'zooniverse/solar-stormwatch',
  'zooniverse/planet-hunters',
  'zooniverse/old-weather',
  'zooniverse/whale-fm',
  'zooniverse/seti-live',
  'zooniverse/seafloor-explorer',
  'zooniverse/cyclone-center',
  'zooniverse/bat-detective',
  'zooniverse/cell-slider',
  'zooniverse/planet-four-ouroboros',
  'zooniverse/worm-watch-lab',
  'zooniverse/plankton-portal-ouroboros',
  'zooniverse/radio-galaxy-zoo',
  'zooniverse/operation-war-diary',
  'zooniverse/disk-detective-1-dot-0',
  'zooniverse/sunspotter',
  'zooniverse/condor-watch',
  'zooniverse/asteroid-zoo',
  'zooniverse/floating-forests-v1',
  'zooniverse/higgs-hunters',
  'zooniverse/science-gossip',
  'zooniverse/orchid-observers',
  'zooniverse/chimp-and-see-ouroboros',
  'zooniverse/measuring-the-anzacs-original',
  'drrogg/annotate',
  'nypl/emigrant-city',
  'bostonpubliclibrary/anti-slavery-manuscripts',
  'judaicadh/scribes-of-the-cairo-geniza',
  // Private Projects
  'a-alam/classification-of-complex-radio-sources',
  'a-gordon/galaxy-tidal-feature-classifications',
  'ahendy/reading-the-fossil-record',
  'ahsiang/auto-foram-batch-2-plus-3-for-anieke',
  'ahsiang/auto-foram-species',
  'alevi98/african-american-civil-war-soldiers-error-correction',
  'alex-andersson/private-radio-transients-r-b-classifier-11-03-2021-14-12-41',
  'alexsokolowska/rockfalls-cerberus-fossae',
  'amandinedd/delve-deep-madcash',
  'amarch/klassifikatsiia-b-ps-baldzhiei-na-osnovie-nalichiia-kh-struktur',
  'ameirshaa/nuclear-track-detector-scans-at-cern',
  'ameliafm612/sami-bars',
  'ans-dot-v/getuigenissen-brugge',
  'apapak/detecting-marine-litter-v-4',
  'apapak/detecting-marine-litter-v-5',
  'apapak/detecting-marine-litter-v-6',
  'apapak/detecting-marine-litter-v-7',
  'apapak/xampelia',
  'aprajita/swdemo',
  'arioeira/the-green-dots-project',
  'ariyanabonab/0-dot-5-oxia-candidates',
  'ariyanabonab/0-dot-8-rockfall-candidates',
  'ariyanabonab/ejecta-candidates',
  'ariyanabonab/oxia-0-dot-6-candidates-excluded-most-overlap',
  'ariyanabonab/rockfall-shadows',
  'ariyanabonab/rockfalls-from-urls',
  'arya75/affirmative-action-annotation',
  'aschig/classifying-lung-nodules',
  'aschig/ztf-astreaks',
  'astellez/tellez-css',
  'astopy/bhh-vetting',
  'astopy/superwasp-miras',
  'astrohayley/ceers-merger-verification',
  'aucklandmuseum/heraldic-beasts-and-where-to-find-them',
  'bathstm/stm-image-sorting',
  'bessest/lifeplan',
  'bgorges/classify-robot-auto-detected-images',
  'bgorges/more-robot-images',
  'bobbenjamin/hii-region-distance-project',
  'bradleyallf/bird-snacks',
  'brandonz/mer-spirit-pancam',
  'brendanwebster/spiral-agn-hunt',
  'brit-org/fort-worth-prairie-phenology-at-brit',
  'bru01/validacion-de-mapas-de-bosques',
  'bw4sz/everglades-watch',
  'c0da/boundarylayer',
  'c0da/untitled-project-10-26-2018-2-56-55-pm',
  'callumbrogan/iwm-digital-collections',
  'caryelisbayonafigueroa/visual-inspection-of-high-normal-flux-ratio-dragns-7-8-2022-10-31-11-am',
  'cbellhouse/hi-jellyfish-classification',
  'cfllopes/splus-cacadores-de-astros',
  'charrod/genome-detectives-2',
  'chris1010010/test-1961-census-liberated',
  'chrispattison/icg-drone-imagery-hack-day',
  'christy-dot-tremonti/manga-metallicity-maps',
  'clara0/classifying-the-stage-of-ram-pressure-stripping-of-galaxies-in-the-hydra-i-cluster',
  'clara0/classify-the-stage-of-ram-pressure-stripping-of-galaxies-in-the-hydra-i-cluster-old-version',
  'clolson/palmer-amaranth-project-3-25-2020-8-30-16-am',
  'cloud-class/clouds-with-a-type',
  'cole-dot-johnston/sphere',
  'cpook/street-scanner',
  'cseidenstuecker/jeder-name-zahlt-dot-dot-dot',
  'cvergara/desy3-xcs',
  'cvergara/desy3-xcs-off-center-images-remade-msl17',
  'danomc/rog-and-dan-do-all-the-clicks',
  'danomc/thales-v2-dot-2',
  'daviana/terrestrial-mammals-of-costa-rica',
  'deadinspiringproject/dead-inspiring',
  'duncanwp/finding-man-made-clouds',
  'dvstark/manga-hi-visual-flagging',
  'ebellm/ztf-dippers',
  'ebiharatns/tns-vs-2022',
  'eduardowoj/classificacao-fotos-fachada',
  'eelsirhc/crater-mapping',
  'emmyd/lunar-landmarks',
  'ericahopkins/lenses',
  'escordato/santa-clara-river-valley-camera-trapping',
  'esterfiorillo/teste-dengue',
  'ezzjcw/mars-in-development',
  'ezzjcw/mars-in-motion-v2',
  'fbarwell/investigating-the-triggering-of-3cr-radio-galaxies',
  'fiona-penguin/penguin-watch-3-dot-0',
  'fltest/phs',
  'flzaah/dental-equipment-recognition-using-artificial-intelligence',
  'fmaviane/arabidopsis-symptoms',
  'fmaviane/downy-mildew-annotation',
  'fullfact/the-full-fact-pilot',
  'fulsdavid/catalina-outer-solar-system-survey-verification',
  'gabriel-azevedo/jellyfish-hsc',
  'gary-complexzoo/anomaly-in-the-emu-zoo-03-11-2021-20-30-42',
  'gbgraham19/embedded-clusters-round-2',
  'gbrammer/charge-high-z-targets',
  'gcwrp/grand-canyon-ecoregion',
  'gekewoudstra/distribution-of-prey-and-predator',
  'getty/gri-artist-letters',
  'getty/gri-shunk-image-tagging',
  'guangwenchen/ai-for-radio-astronomy',
  'h-spiers/etch-a-cell-mito-mega-mix',
  'h-spiers/etch-a-cell-nuclei-explorer',
  'h-spiers/science-scribbler-all-or-nothing',
  'hellenmonteirop/a-quest-for-jellyfish-galaxies-in-s-plus-data',
  'henry-dot-leopold/apollo',
  'henrycooke/classifying-c60-si-111-spm-images',
  'highzgal/claudia',
  'hiro-ono/ai4mars-gold-standard-labeling',
  'hiro-ono/the-planet-arroyo',
  'hollyel/nmnh-epicc-specimen-assessment',
  'hughdickinson/superwasp-bhh-gold-standard',
  'hughdickinson/wisp-passive-galaxy-search',
  'hughdickinson/zaks-magical-my-eyes-catalogue',
  'hunterlc/elves-images',
  'hunterlc/larger-satellite-identification',
  'hunterlc/satellite-galaxies-identification',
  'hunterlc/satellite-inspection-deep-dive',
  'imjs/roof-shape',
  'inigoval/mightee-test-set',
  'ioannis666/detecting-marine-litter-v-1',
  'ioannis6666/detecting-marine-litter-v-2',
  'itrharrison/superclassify',
  'j-dot-popp/hsc-clump-ml-checker',
  'j-dot-sadek/historia-plantarum',
  'j-dot-sadek/historia-plantarum-2',
  'jaygattuso/cartes-de-visite-faces',
  'jen-dot-schultze/northern-illinois-wildlife',
  'jenwalls/aces-compact-source-removal',
  'jeyhansk/ceers-visual-classifications',
  'jimmafeni/road-cam-annotation',
  'jmaple/napc-summer-2022',
  'jmschell/tar-pits-zooniverse-project',
  'jnaiman/nlp-test',
  'jnaiman/prototype-document-layout-analysis',
  'joaofranca/lastberu',
  'jonesr8/phoenix-zoo-trailblazers-wildlife-watch',
  'jonnypierce/do-agn-triggering-mechanisms-vary-with-radio-power',
  'joseph-meli/the-malta-dockyard-collection',
  'justacea/genome-instability',
  'jypark/something-odd-about-that-plant',
  'karts/eye-on-the-apostles',
  'kcotar/galah-spectra',
  'kerrypaterson/saguaro-ml',
  'klmasters/spiral-mask-inspection',
  'kpillai/masonry-crack-pattern-similarity-assessment-all-images',
  'kpillai/masonry-crack-pattern-similarity-assessment-fe-images',
  'krojas26/experts-visual-inspection-experiment',
  'kunzel/getting-ready-for-mars',
  'larondalab/egg-hunt-ovarian-follicle-identification',
  'lauraneckstein/scribes-of-the-cairo-geniza',
  'leeskelvin/green-valley-census',
  'lennea/testing-itcz-image-classification',
  'lesb20/x-ray-lab-lets-go',
  'llomeli/cosmos-jwst-galaxy',
  'ltom/artillery-crater-analysis-and-detection-engine-arcade',
  'lucasgautheron/pretty-diagrams-and-the-evolution-of-costly-cultural-norms',
  'maayane/ztf-transients-hosts-identification',
  'manasi99/classifying-data-from-the-new-pipeline',
  'manasisharma/gattini-ir-ml-classifier',
  'manateetristanity/whats-in-a-whistle',
  'mangroveturtle/mangrove-spy-usvi',
  'manolopoulaki/xcs-dr2-sdss-cluster-zoo',
  'marchett/icy-world-surface-analogues',
  'marckuchner/galex-zoo',
  'mariateresanardone/relabelling-jwst-galaxy-images',
  'matheusbarrosp/dataset-mp-pavimentacao',
  'mathphys/mergers-among-sdss-agn-hosts',
  'matthewtpenny/testmishaps',
  'max-dot-larreur/2022-field-season',
  'mbatsaris/detecting-marine-litter-v-3',
  'mbatsaris1/detecting-marine-litter-v-10',
  'mbatsaris1/detecting-marine-litter-v-8',
  'mbatsaris1/detecting-marine-litter-v-9',
  'mbbagley/ceers-science-sprint',
  'mbbagley/egs-classifications',
  'mbbagley/werls-classifications',
  'md68135/nfn-private-project',
  'mdipompeo/wise-hsc-agn',
  'meghanparry/wilson-historic-district',
  'midniteclub/sud-project',
  'miglioa/m4',
  'mike-dot-jones-dot-astro/blue-blobs',
  'mike-dot-jones-dot-astro/ufds-in-smudges',
  'mikewalmsley/galaxy-judges',
  'mjh22/lofar-galaxy-zoo',
  'mjh22/mightee-galaxy-zoo',
  'mnmarjadi/internal-test',
  'mouse13/deeplense-sample',
  'mph51/cambridge-university-herbarium-elm-leaf-project',
  'mschwamb/planet-four-boulders',
  'msemczuk/warps-zoo-tng',
  'nationallibraryofnewzealand/cartes-de-re-visites',
  'ncoco/foto-fachada-nati',
  'ncoco/foto-fachada-rha',
  'ndeg/wallaby-decals-trial',
  'nelvy/beard-clasification-test',
  'nelvy/beard-satellites-clasification-test2',
  'newberry/art-in-miniature',
  'newberry/postcard-tag-old',
  'nicholasfoster/te-manahuna-aoraki',
  'nicoadams/environment-project-clump-vetting',
  'nora-dot-eisner/classifying-the-classified',
  'oboucher/identification-of-contrails',
  'panthera-research/private-camera-catalogue',
  'peak-finder/diffraction-peak-labelling',
  'penguintom79/kittiwake-project',
  'petitpadawan/soleil-detection',
  'peto582/linear-object-classification',
  'psweeney/marginal-botany',
  'ptsws/fossil',
  'ptsws/fossil2',
  'ptsws/hsc-ssp-deep',
  'rachaelorben/oregon-seabirds',
  'radurevutchi/sound-descriptors-actions',
  'rahulsrajeshh/neuroai-2',
  'rahulsrajeshh/orchvate-da-aptitude-test-new',
  'rahulsrajeshh/orchvate-da-aptitude-test-september-2024',
  'rdonner/subaru-galaxies',
  'restor/tag-trees-deprecated',
  'rns461/deeds-3-13-2025-4-39-35-pm',
  'rswcit/ztf-public-msip-project',
  'safmcadmin/fishstory-validation-project',
  'sandorkruk/bars-jwst',
  'sassydumbledore/chimp-and-see-miniproject-draconian-kerfuffle',
  'sassydumbledore/chimp-matching-mini-project-ethereal-lotus',
  'sdp27/the-osteoarthritis-x-ray-classification-research-project',
  'serc/chesapeake-bay-parasite-project',
  'serc/invader-id-target-taxa',
  'serc/oyster-cam',
  'serjeant/galaxy-smudges',
  'sherman-dot-sydney/b3-catalogv3-vi',
  'sherman-dot-sydney/b4-catalogv3-vi',
  'sherman-dot-sydney/b5-catalogv3-vi',
  'sherman-dot-sydney/b6-catalogv3-vi',
  'sherman-dot-sydney/b6b-catalogv3-vi',
  'sherman-dot-sydney/b6c-catalogv3-vi',
  'siljeg/apertif-catalogue',
  'sladeaa/soundscape-monitoring',
  'sophmjewell/desi-disk-dominated-agn-hosts',
  'squidgame/anita',
  'squidgame/dr-poissant',
  'squidgame/ihncheol',
  'squidgame/mason',
  'squidgame/micky',
  'squidgame/rachel',
  'squidgame/stefan',
  'stephenresearch/arctic-aerial-surveys',
  'stephenresearch/red-panda-behaviour',
  'stothart/sable-island-horse-condition-project',
  'suja82/dustdevilsctx',
  'surhudm/barred-galaxy-classification-hsc',
  'swapnaneel/finding-ring-dwarf-galaxy',
  'sweetime/jellyfish-galaxies',
  'sydney-b-sherman/shela-b3-eazy-py-massive-vi-number-2',
  'sydney-b-sherman/shela-scirange-m-1e11-visual-inspection',
  'sydney-sherman19/shela-b5-eazy-py-massive-vi',
  'sydney-sherman19/shela-b6-eazy-py-massive-vi',
  'sydneyunilibrary/detective-fiction',
  'sydsherman19/shela-b4-eazy-py-massive-vi',
  'tbutrum/overlap-zoo',
  'tharinduj/g-band-variables-test',
  'tstewart656/morphology-of-spogs',
  'vardanp91/frick',
  'vmehta/splash-sxdf-eelg',
  'warworld2/ww2dead',
  'wcagizmo/early-christian-papyri',
  'weijmans/hi-weave-apertif-classification',
  'weiyinko/find-the-watermelons-6-22-2017-6-09-17-pm',
  'westerlund2/wd2-variable-star-zoo',
  'wkiri/mars-landmarks',
  'wragge/sydney-stock-exchange',
  'yjangordon/vlass-variables',
  'yntzevanderhoek/nkuba',
  'zoeyyy/glitch-classificationslug',
  // Assorted Special Cases
  'acre-ar/meteororum-ad-extremum-terrae', // Subject image sizes difficult in FEM's classifier layout
  'alicemead/sudan-road-access-logistics-cluster',
  'aprajita/space-warps-des-vision-transformer', // Subject image sizes difficult in FEM's classifier layout
  'artem-dot-reshetnikov/saint-george-on-a-bike',
  'astorino/sovraimpressioni', // Issue with its combo task
  'astro-lab-ncmns/spiral-graph', // Freehand segment line and freehand shape deprecated from FEM
  'cmnbotany/notes-from-nature-capture-the-collections',
  'dwhiter/aurora-zoo', // Subject image sizes difficult in FEM's classifier layout
  'gaia-zooniverse/gaia-vari', // SVG subjects aren't supported in FEM
  'hripsi-19/atmoselec-atmospheric-electricity-for-climate', // Issue with its combo task
  'hugo-ferreira/where-is-spoony', // Uses experimental "slider" subtask
  'jenbays/beaver-dams', // CSSI project
  'low-sky/bubblezoo-v1', // Oval drawing tool is a worse experience in FEM
  'mappingprejudice/mapping-prejudice',
  'md68135/notes-from-nature-big-bee-bonanza',
  'md68135/notes-from-nature-calbug', // Dependent dropdowns aren't supported in FEM
  'md68135/notes-from-nature-capturing-californias-flowers', // Dependent dropdowns aren't supported in FEM
  'md68135/notes-from-nature-digitizing-biological-collections-in-canada',
  'md68135/notes-from-nature-flora-of-texas-and-oklahoma', // Dependent dropdowns aren't supported in FEM
  'md68135/notes-from-nature-herbarium', // Dependent dropdowns aren't supported in FEM
  'md68135/notes-from-nature-southeastern-us-biodiversity',
  'md68135/notes-from-nature-terrestrial-parasite-tracker', // Dependent dropdowns aren't supported in FEM
  'md68135/notes-from-nature-wedigflplants',
  'md68135/notes-from-nature-natural-history-at-rom-revealed',
  'meteonetwork/redata',
  'mikewalmsley/galaxy-zoo-mobile',
  'mollysimon/galaxy-zoo-crowdsourcing-activity', // Classrooms
  'msbrhonclif/science-scribbler-key2cat', // Subject image sizes difficult in FEM's classifier layout
  'msbrhonclif/science-scribbler-placenta-profiles', // Subject image sizes difficult in FEM's classifier layout
  'mschwamb/planet-four', // Uses experimental "fan tool"
  'nora-dot-eisner/planet-hunters-tess-mobile',
  'panettafordham/shadows-on-stone-identifying-sing-sings-incarcerated',
  'penguintom79/penguin-watch', // Uses experimental "shortcut"
  'penguintom79/seabirdwatch', // Uses experimental "shortcut"
  'projectenigma/enigmatic-near-earth-visitors', // Video in a flipbook isn't supported in FEM
  'rsengar/einstein-at-home-pulsar-seekers', // Feedback per step isn't supported in FEM
  'sassydumbledore/chimp-and-see', // Video in a flipbook isn't supported in FEM
  'tawakitom/penguins-from-above', // Subject image sizes difficult in FEM's classifier layout
  'tingard/galaxy-builder', // custom slider interface on finished project
  'watchablewildlife/nebraska-wildlife-watch',
  'wildcam/wildcam-darien',
  'wwt/stream-team-emerging-insect-explorer',
  'xbonnin/solar-radio-burst-tracker', // Freehand segment line and freehand shape deprecated from FEM
  'zooniverse/floating-forests',
  'zooniverse/intro2astro-hubbles-law', // Classrooms
  'zooniverse/measuring-the-anzacs', // Classrooms
  'zooniverse/zooniverse-in-schools', // Classrooms
  // Audio Projects
  'annelistens/ocean-voices',
  'cblume27/rhythms-of-the-night',
  'creisdorf/fire-and-birds',
  'creisdorf/savanna-spy-sound', // Audio subject with spectrogram isn't supported in FEM
  'cslab-upm/sky-sounds',
  'hannah-dot-slesinski/chirp-check', // Audio subject with spectrogram isn't supported in FEM
  'laac-lscp/maturity-of-baby-sounds', // Audio subjects aren't supported in FEM's classifier
  'laaczooniverse/what-do-babies-say',
  'library-of-congress/transcribe-american-dialect-recordings',
  'lydiakatsis/forest-sounds',
  'marywestwood/the-cricket-wing', // Audio subject with spectrogram isn't supported in FEM
  'ollibruuh/bird-find', // Audio subjects aren't supported in FEM's classifier
  'ollibruuh/frog-find', // Audio subjects aren't supported in FEM's classifier
  'sandorkruk/istrox',
  'sladeaa/audioclassification',
  'uw-leap/tots-and-tunes',
  'wingkitty/filk-archive',
  'tuc04/ruby-3-dot-2-testing-2-4-2026-7-07-26-pm',
  'yli/humbug' // Audio subject with spectrogram isn't supported in FEM
]

export default PFE_SLUGS
