module.exports =
  bezier: require './poly-curve'
  circle: require './circle'
  column: require './column-rectangle'
  ellipse: require './ellipse'
  freehandLine: require './freehand-line'
  freehandShape: require './freehand-shape'
  grid: require './grid'
  line: require './line'
  point: require './point'
  polygon: require './polygon'
  rectangle: require './rectangle'
  triangle: require './triangle'
