module.exports =
  point: require './point'
  line: require './line'
  polygon: require './polygon'
  rectangle: require './rectangle'
  circle: require './circle'
  ellipse: require './ellipse'
  bezier: require './poly-curve'
  column: require './column-rectangle'
  grid: require './grid'
  triangle: require './triangle'