const languages = [
  { value: 'af', label: 'Afrikaans' },
  { value: 'sq', label: 'Albanian' },
  { value: 'gsw-fr', label: 'Alsatian (France)' },
  { value: 'am-et', label: 'Amharic (Ethiopia)' },
  { value: 'ar', label: 'Arabic' },
  { value: 'hy', label: 'Armenian' },
  { value: 'as-in', label: 'Assamese (India)' },
  { value: 'az', label: 'Azeri' },
  { value: 'ba-ru', label: 'Bashkir (Russia)' },
  { value: 'eu', label: 'Basque' },
  { value: 'be', label: 'Belarusian' },
  { value: 'bn-bd', label: 'Bengali (Bangladesh)' },
  { value: 'bn-in', label: 'Bengali (India)' },
  { value: 'bs-cyrl-ba', label: 'Bosnian (Cyrillic, Bosnia and Herzegovina)' },
  { value: 'bs-latn-ba', label: 'Bosnian (Latin, Bosnia and Herzegovina)' },
  { value: 'br-fr', label: 'Breton (France)' },
  { value: 'bg', label: 'Bulgarian' },
  { value: 'ca', label: 'Catalan' },
  { value: 'zh-cn', label: 'Chinese (Simplified)' },
  { value: 'zh-tw', label: 'Chinese (Traditional)' },
  { value: 'hr', label: 'Croatian' },
  { value: 'cs', label: 'Czech' },
  { value: 'da', label: 'Danish' },
  { value: 'prs-af', label: 'Dari (Afghanistan)' },
  { value: 'div', label: 'Divehi' },
  { value: 'nl', label: 'Dutch' },
  { value: 'en', label: 'English' },
  { value: 'en-gb', label: 'English (United Kingdom)' },
  { value: 'en-us', label: 'English (United States)' },
  { value: 'et', label: 'Estonian' },
  { value: 'fo', label: 'Faroese' },
  { value: 'fil-ph', label: 'Filipino (Philippines)' },
  { value: 'fi', label: 'Finnish' },
  { value: 'fr', label: 'French' },
  { value: 'gl', label: 'Galician' },
  { value: 'ka', label: 'Georgian' },
  { value: 'de', label: 'German' },
  { value: 'el', label: 'Greek' },
  { value: 'kl-gl', label: 'Greenlandic (Greenland)' },
  { value: 'gu', label: 'Gujarati' },
  { value: 'ha-latn-ng', label: 'Hausa (Latin, Nigeria)' },
  { value: 'he', label: 'Hebrew' },
  { value: 'hi', label: 'Hindi' },
  { value: 'hu', label: 'Hungarian' },
  { value: 'is', label: 'Icelandic' },
  { value: 'ig-ng', label: 'Igbo (Nigeria)' },
  { value: 'id', label: 'Indonesian' },
  { value: 'iu-latn-ca', label: 'Inuktitut (Latin, Canada)' },
  { value: 'iu-cans-ca', label: 'Inuktitut (Syllabics, Canada)' },
  { value: 'ga-ie', label: 'Irish (Ireland)' },
  { value: 'xh-za', label: 'isiXhosa (South Africa)' },
  { value: 'zu-za', label: 'isiZulu (South Africa)' },
  { value: 'it', label: 'Italian' },
  { value: 'ja', label: 'Japanese' },
  { value: 'kn', label: 'Kannada' },
  { value: 'kk', label: 'Kazakh' },
  { value: 'km-kh', label: 'Khmer (Cambodia)' },
  { value: 'qut-gt', label: 'K\'iche (Guatemala)' },
  { value: 'rw-rw', label: 'Kinyarwanda (Rwanda)' },
  { value: 'sw', label: 'Kiswahili' },
  { value: 'kok', label: 'Konkani' },
  { value: 'ko', label: 'Korean' },
  { value: 'ky', label: 'Kyrgyz' },
  { value: 'lo-la', label: 'Lao (Lao P.D.R.)' },
  { value: 'lv', label: 'Latvian' },
  { value: 'lt', label: 'Lithuanian' },
  { value: 'wee-de', label: 'Lower Sorbian (Germany)' },
  { value: 'lb-lu', label: 'Luxembourgish (Luxembourg)' },
  { value: 'mk', label: 'Macedonian' },
  { value: 'ms', label: 'Malay' },
  { value: 'ml-in', label: 'Malayalam (India)' },
  { value: 'mt-mt', label: 'Maltese (Malta)' },
  { value: 'mi-nz', label: 'Maori (New Zealand)' },
  { value: 'arn-cl', label: 'Mapudungun (Chile)' },
  { value: 'mr', label: 'Marathi' },
  { value: 'moh-ca', label: 'Mohawk (Mohawk)' },
  { value: 'mn', label: 'Mongolian' },
  { value: 'ne-np', label: 'Nepali (Nepal)' },
  { value: 'no', label: 'Norwegian' },
  { value: 'oc-fr', label: 'Occitan (France)' },
  { value: 'or-in', label: 'Oriya (India)' },
  { value: 'ps-af', label: 'Pashto (Afghanistan)' },
  { value: 'fa', label: 'Persian' },
  { value: 'pl', label: 'Polish' },
  { value: 'pt', label: 'Portuguese' },
  { value: 'pa', label: 'Punjabi' },
  { value: 'quz-bo', label: 'Quechua (Bolivia)' },
  { value: 'quz-ec', label: 'Quechua (Ecuador)' },
  { value: 'quz-pe', label: 'Quechua (Peru)' },
  { value: 'ro', label: 'Romanian' },
  { value: 'rm-ch', label: 'Romansh (Switzerland)' },
  { value: 'ru', label: 'Russian' },
  { value: 'sa', label: 'Sanskrit' },
  { value: 'sr', label: 'Serbian' },
  { value: 'nso-za', label: 'Sesotho sa Leboa (South Africa)' },
  { value: 'tn-za', label: 'Setswana (South Africa)' },
  { value: 'si-lk', label: 'Sinhala (Sri Lanka)' },
  { value: 'sk', label: 'Slovak' },
  { value: 'sl', label: 'Slovenian' },
  { value: 'es', label: 'Spanish' },
  { value: 'sv', label: 'Swedish' },
  { value: 'syr', label: 'Syriac' },
  { value: 'tg-cyrl-tj', label: 'Tajik (Cyrillic, Tajikistan)' },
  { value: 'tzm-latn-dz', label: 'Tamazight (Latin, Algeria)' },
  { value: 'ta', label: 'Tamil' },
  { value: 'tt', label: 'Tatar' },
  { value: 'te', label: 'Telugu' },
  { value: 'th', label: 'Thai' },
  { value: 'bo-cn', label: 'Tibetan (PRC)' },
  { value: 'tr', label: 'Turkish' },
  { value: 'tk-tm', label: 'Turkmen (Turkmenistan)' },
  { value: 'ug-cn', label: 'Uighur (PRC)' },
  { value: 'uk', label: 'Ukrainian' },
  { value: 'wen-de', label: 'Upper Sorbian (Germany)' },
  { value: 'ur', label: 'Urdu' },
  { value: 'uz', label: 'Uzbek' },
  { value: 'vi', label: 'Vietlabelse' },
  { value: 'cy', label: 'Welsh' },
  { value: 'wo-sn', label: 'Wolof (Senegal)' },
  { value: 'sah-ru', label: 'Yakut (Russia)' },
  { value: 'ii-cn', label: 'Yi (PRC)' },
  { value: 'yo-ng', label: 'Yoruba (Nigeria)' }
];

export default languages;
