export default {
  en: 'English',
  ar: 'العربية',
  cs: 'Čeština',
  de: 'Deutsch',
  es: 'Español',
  el: 'Ελληνικά',
  fr: 'Francais',
  he: 'עברית',
  hi: 'हिन्दी',
  it: 'Italiano',
  ja: '日本人',
  kn: 'ಕನ್ನಡ',
  ko: '한국어',
  nl: 'Nederlands',
  pl: 'Polski',
  pt: 'Português',
  ru: 'русский',
  sv: 'Svenska',
  uk: 'українська мова',
  'zh-cn': '简体中文',
  'zh-tw': '繁體中文'
};
