name: Deploy to Zooniverse Static

on:
    # Run this workflow from other workflows
    workflow_call:
      inputs:
        commit_id: 
          description: 'HEAD commit hash'
          required: true
          type: string
        deploy_url:
          description: 'Deployed URL'
          required: true
          type: string
        job_name:
          description: 'Job name to report on'
          required: true
          type: string
        script:
          description: 'npm build script'
          required: true
          type: string
        source:
          default: './dist'
          description: 'Source directory'
          required: false
          type: string
        target:
          description: 'Path to target folder'
          required: true
          type: string
        title:
          description: 'Notification title'
          required: true
          type: string
      secrets:
        creds:
          required: true
        slack_webhook_url:
          required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEAD_COMMIT: ${{ inputs.commit_id }}
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.creds }}

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Node.js build
      id: build
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run ${{ inputs.script }}

    - name: Write commit_id.txt
      run: echo ${HEAD_COMMIT} > ${{ inputs.source }}/commit_id.txt

    - name: Upload to blob storage
      id: upload
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload \
              --account-name zooniversestatic \
              --content-cache-control 'public, max-age=60' \
              --container-name '$web' \
              --name '${{ inputs.target }}/index.html' \
              --file '${{ inputs.source }}/index.html'
            rm ${{ inputs.source }}/index.html
            az storage blob upload \
              --account-name zooniversestatic \
              --content-cache-control 'public, max-age=60' \
              --container-name '$web' \
              --name '${{ inputs.target }}/commit_id.txt' \
              --file '${{ inputs.source }}/commit_id.txt'
            rm ${{ inputs.source }}/commit_id.txt
            az storage blob upload-batch \
              --account-name zooniversestatic \
              --content-cache-control 'public, immutable, max-age=604800' \
              --destination '$web/${{ inputs.target }}' \
              --source ${{ inputs.source }}

  slack_notification:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
        with:
          job_name: ${{ inputs.job_name }} / deploy
          fields: took
          status: custom
          custom_payload: |
            {
              "channel": "#deploys",
              "icon_emoji": ":octocat:",
              "username": "Deploy Action",
              "attachments": [{
                "color": '${{ needs.deploy.result }}' === 'success' ? 'good' : '${{ needs.deploy.result }}' === 'failure' ? 'danger' : 'warning',
                "mrkdwn_in": ["text"],
                "author_name": "${{ github.actor }}",
                "author_link": "https://github.com/${{ github.actor }}/",
                "author_icon": "https://github.com/${{ github.actor }}.png?size=40",
                "title": "${{ inputs.title }}",
                "title_link": "${{ inputs.deploy_url }}",
                "fields": [
                    {
                        "title": "Status",
                        "value": '${{ needs.deploy.result }}' === 'success' ? `:white_check_mark: Success in ${process.env.AS_TOOK}` : '${{ needs.deploy.result }}' === 'failure' ? ':x: Failed' : ':warning: Warning',
                        "short": true
                    },
                    {
                        "title": "Triggered by",
                        "value": "${{ github.event_name }}",
                        "short": true
                    },
                    {
                        "title": "Initiated by",
                        "value": "<https://github.com/${{ github.repository }}/pull/${{ github.event.number }}|${{ github.event.pull_request.title }}>"
                    },
                    {
                        "title": "Run Link",
                        "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                ],
                "thumb_url": "https://raw.githubusercontent.com/zooniverse/Brand/master/style%20guide/logos/zooniverse-emblem/zooniverse-logo-teal.png",
                "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}> #${{ github.run_number }}",
                "footer_icon": "https://www.zooniverse.org/favicon.ico"
              }]
            }
