name: Deploy to Zooniverse Static

on:
    # Run this workflow from other workflows
    workflow_call:
      inputs:
        source:
          description: 'Source package'
          required: true
          type: string
        target:
          description: 'Path to target folder'
          required: true
          type: string
      secrets:
        creds:
          required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download source
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.source }}

    - uses: azure/login@v1
      with:
          creds: ${{ secrets.creds }}

    - name: Upload to blob storage
      id: upload
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload \
              --account-name zooniversestatic \
              --content-cache-control 'public, max-age=60' \
              --container-name '$web' \
              --name '${{ inputs.target }}/index.html' \
              --file './index.html'
            rm ./index.html
            az storage blob upload \
              --account-name zooniversestatic \
              --content-cache-control 'public, max-age=60' \
              --container-name '$web' \
              --name '${{ inputs.target }}/commit_id.txt' \
              --file './commit_id.txt'
            rm ./commit_id.txt
            az storage blob upload-batch \
              --account-name zooniversestatic \
              --content-cache-control 'public, immutable, max-age=604800' \
              --destination '$web/${{ inputs.target }}' \
              --source ./
